name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            riccardotornesello/hello-world-http-server
            ghcr.io/${{ github.repository }}

      - name: Extract metadata for tester image
        id: meta-tester
        uses: docker/metadata-action@v5
        with:
          images: |
            riccardotornesello/hello-world-http-server
            ghcr.io/${{ github.repository }}
          flavor: |
            suffix=-tester

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build and push tester Docker images
        id: push-tester
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.tester
          build-args: VERSION=${{ github.event.release.tag_name }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-tester.outputs.tags }}
          labels: ${{ steps.meta-tester.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Generate DockerHub artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/riccardotornesello/hello-world-http-server
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate DockerHub tester artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/riccardotornesello/hello-world-http-server
          subject-digest: ${{ steps.push-tester.outputs.digest }}
          push-to-registry: true

      - name: Generate GitHub artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate GitHub tester artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push-tester.outputs.digest }}
          push-to-registry: true
